xcopy *.h ..\back\sources\ /s /h /c /y 
xcopy *.c ..\back\sources\ /s /h /c /y 
xcopy *.hpp ..\back\sources\ /s /h /c /y 
xcopy *.cpp ..\back\sources\ /s /h /c /y 
xcopy *.vcproj ..\back\sources\ /s /h /c /y 
xcopy *.vcxproj ..\back\sources\ /s /h /c /y 
xcopy *.filters ..\back\sources\ /s /h /c /y 
xcopy *.sln ..\back\sources\ /s /h /c /y 
xcopy *.iex ..\back\sources\ /s /h /c /y 
xcopy *.lua ..\back\sources\ /s /h /c /y 
xcopy *.pkg ..\back\sources\ /s /h /c /y
xcopy *.lua ..\back\sources\ /s /h /c /y
xcopy *.rc ..\back\sources\ /s /h /c /y
xcopy *.rc2 ..\back\sources\ /s /h /c /y
xcopy *.bmp ..\back\sources\ /s /h /c /y
xcopy *.jpg ..\back\sources\ /s /h /c /y
xcopy *.tga ..\back\sources\ /s /h /c /y
xcopy *.bat ..\back\sources\ /s /h /c /y
xcopy *.dsp ..\back\sources\ /s /h /c /y 
xcopy *.dsw ..\back\sources\ /s /h /c /y 
xcopy *.inl ..\back\sources\ /s /h /c /y 
